### ISSUE TITLE
Option to include custom headers on QueryBuilders

### ISSUE THREAD

**Issue by lasantosr** [puetzp/prometheus-http-query#5]
I've seen #3 but the workaround only provides a way of setting static headers for every request.

There is no way to include a dynamic header (for example the tenant being queried to [Cortex](https://cortexmetrics.io/docs/api/#authentication)) without re-creating a reqwest client on each query.

**Comment by puetzp** [comment]
Thanks for the suggestion. I see why creating a new `reqwest::Client` would be too cumbersome if headers indeed vary from query to query.

**Comment by lasantosr** [comment]
@puetzp Can you create a new release with the changes?
