### ISSUE TITLE
Client panicked when content-type in response is `application/json; charset=utf-8`

### ISSUE THREAD

**Issue by imtsuki** [puetzp/prometheus-http-query#7]
I'm dealing with a prometheus server that sets its content type in responses to `application/json; charset=utf-8`. This line causes panic with message: called `Result::unwrap_err()` on an `Ok` value:

https://github.com/puetzp/prometheus-http-query/blob/ae2d6a5f99a86d394f97cf04dea399b0d3a78a0a/src/client.rs#L324-L330

**Comment by puetzp** [comment]
Yeah I definitely need to change that part. The basic idea behind checking the Content-Type was to deserialize responses (successes or failures) from a Prometheus server as JSON, but also provide a fallback if the response comes from an intermediate proxy that returns plain text in the response body.
But there are certainly better ways to do it. I will look into it.
